apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: gcr.io/dev-workloads/flask-app
        name: flask-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    type: LoadBalancer
  selector:
    app: flask-app
