name: Build and push with GitHub Actions
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      
      - name: build-image-and-containerize
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: python-build
          tags: ibrahim
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
